try{
    console.log(a)
}catch(error){
    console.log(error)
}
console.log(3+7)